+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed Apr  5 20:04:19 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL etcd
+ pkgs=etcd
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs etcd --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp85vjd9nm
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp85vjd9nm
+ systemctl start etcd
Job for etcd.service failed because the control process exited with error code.
See "systemctl status etcd.service" and "journalctl -xeu etcd.service" for details.
++ awk -F - '{print$2}'
++ rpm -qa etcd
+ version=3.4.14
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Wed Apr  5 20:05:40 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Apr  5 20:05:41 2023 - INFO  - Start to run test.
+ systemctl status etcd
+ grep 'active (running)'
+ CHECK_RESULT 1 0 0 'Check etcd.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcd.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcd.service start failed'
+ LOG_ERROR 'Check etcd.service start failed'
+ message='Check etcd.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcd.service start failed'
Wed Apr  5 20:05:42 2023 - ERROR - Check etcd.service start failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 30'
+ message='oe_test_etcd_01.sh line 30'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 30'
Wed Apr  5 20:05:43 2023 - ERROR - oe_test_etcd_01.sh line 30
+ '[' 0 -eq 1 ']'
+ return 0
+ etcd --help
+ grep -i Usage:
+ CHECK_RESULT 1 0 0 'Check etcd --help failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcd --help failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcd --help failed.'
+ LOG_ERROR 'Check etcd --help failed.'
+ message='Check etcd --help failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcd --help failed.'
Wed Apr  5 20:05:45 2023 - ERROR - Check etcd --help failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 32'
+ message='oe_test_etcd_01.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 32'
Wed Apr  5 20:05:45 2023 - ERROR - oe_test_etcd_01.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
++ etcd --version
++ awk '{print $3}'
++ head -1
+ test unsupported == 3.4.14
+ CHECK_RESULT 1 0 0 'Check etcd --version failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcd --version failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcd --version failed.'
+ LOG_ERROR 'Check etcd --version failed.'
+ message='Check etcd --version failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcd --version failed.'
Wed Apr  5 20:05:47 2023 - ERROR - Check etcd --version failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 34'
+ message='oe_test_etcd_01.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 34'
Wed Apr  5 20:05:48 2023 - ERROR - oe_test_etcd_01.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
++ etcdctl version
++ awk '{print $3}'
++ head -1
+ test 3.4.14 == 3.4.14
+ CHECK_RESULT 0 0 0 'Check etcdctl version failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl version failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ etcdctl help
+ grep -i USAGE:
USAGE:
+ CHECK_RESULT 0 0 0 'Check etcdctl help failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl help failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 put a 123
+ grep -i OK
{"level":"warn","ts":"2023-04-05T20:05:55.949+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-c1ace76a-adf4-4fa3-952f-7c40a5d10b4f/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl --endpoints put command failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl --endpoints put command failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl --endpoints put command failed.'
+ LOG_ERROR 'Check etcdctl --endpoints put command failed.'
+ message='Check etcdctl --endpoints put command failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl --endpoints put command failed.'
Wed Apr  5 20:05:56 2023 - ERROR - Check etcdctl --endpoints put command failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 40'
+ message='oe_test_etcd_01.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 40'
Wed Apr  5 20:05:57 2023 - ERROR - oe_test_etcd_01.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 get a
+ grep 123
{"level":"warn","ts":"2023-04-05T20:06:03.434+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-a8947fab-2c20-4215-8bac-17105781e87c/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl --endpoints get command failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl --endpoints get command failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl --endpoints get command failed.'
+ LOG_ERROR 'Check etcdctl --endpoints get command failed.'
+ message='Check etcdctl --endpoints get command failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl --endpoints get command failed.'
Wed Apr  5 20:06:04 2023 - ERROR - Check etcdctl --endpoints get command failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 42'
+ message='oe_test_etcd_01.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 42'
Wed Apr  5 20:06:05 2023 - ERROR - oe_test_etcd_01.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 get a -w=json
+ grep version
{"level":"warn","ts":"2023-04-05T20:06:10.985+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-f3e6e942-fb4a-486a-a427-78fb01cbe0e6/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl --endpoints get -w=json command failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl --endpoints get -w=json command failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl --endpoints get -w=json command failed.'
+ LOG_ERROR 'Check etcdctl --endpoints get -w=json command failed.'
+ message='Check etcdctl --endpoints get -w=json command failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl --endpoints get -w=json command failed.'
Wed Apr  5 20:06:11 2023 - ERROR - Check etcdctl --endpoints get -w=json command failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 44'
+ message='oe_test_etcd_01.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 44'
Wed Apr  5 20:06:12 2023 - ERROR - oe_test_etcd_01.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 del a
+ grep 1
{"level":"warn","ts":"2023-04-05T20:06:18.488+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-4dc43d78-3c68-4828-aa27-a8ed7a7821dc/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl --endpoints del command failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl --endpoints del command failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl --endpoints del command failed.'
+ LOG_ERROR 'Check etcdctl --endpoints del command failed.'
+ message='Check etcdctl --endpoints del command failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl --endpoints del command failed.'
Wed Apr  5 20:06:19 2023 - ERROR - Check etcdctl --endpoints del command failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 46'
+ message='oe_test_etcd_01.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 46'
Wed Apr  5 20:06:20 2023 - ERROR - oe_test_etcd_01.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 del a
+ grep 0
{"level":"warn","ts":"2023-04-05T20:06:25.967+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-1e0ce23a-a570-4071-a835-17f38752bf41/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl --endpoints del command failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl --endpoints del command failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl --endpoints del command failed.'
+ LOG_ERROR 'Check etcdctl --endpoints del command failed.'
+ message='Check etcdctl --endpoints del command failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl --endpoints del command failed.'
Wed Apr  5 20:06:26 2023 - ERROR - Check etcdctl --endpoints del command failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 48'
+ message='oe_test_etcd_01.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 48'
Wed Apr  5 20:06:27 2023 - ERROR - oe_test_etcd_01.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed Apr  5 20:06:28 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Apr  5 20:06:29 2023 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Apr  5 20:06:30 2023 - INFO  - Start to restore the test environment.
+ systemctl stop etcd
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp85vjd9nm ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp85vjd9nm
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed Apr  5 20:06:56 2023 - INFO  - End to restore the test environment.
