+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ main
+++ type -t post_test
++ '[' -n '' ']'
++ trap POST_TEST_DEFAULT EXIT INT HUP TERM
++ rpm -qa
++ grep expect
+++ type -t config_params
++ '[' -n '' ']'
+++ type -t pre_test
++ '[' -n '' ']'
+++ type -t run_test
++ '[' -n '' ']'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed Apr  5 22:05:57 2023 - INFO  - Start to prepare the test environment.
+ Pre_Test
+ DNF_INSTALL 'fastdfs* libfdfsclient net-tools'
+ pkgs='fastdfs* libfdfsclient net-tools'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'fastdfs* libfdfsclient net-tools' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp34fz2_0g
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp34fz2_0g
+ cp /etc/fdfs/client.conf.sample ./client.conf
cp: cannot stat '/etc/fdfs/client.conf.sample': No such file or directory
+ cp /etc/fdfs/storage.conf.sample ./storage.conf
cp: cannot stat '/etc/fdfs/storage.conf.sample': No such file or directory
+ cp /etc/fdfs/tracker.conf.sample ./tracker.conf
cp: cannot stat '/etc/fdfs/tracker.conf.sample': No such file or directory
+ mkdir -p /tmp/guochenyang/1 /tmp/guochenyang/2 /tmp/guochenyang/3
+ sed -i '/base_path/s/\/home\/yuqing\/fastdfs/\/tmp\/guochenyang\/1/g' ./client.conf
sed: can't read ./client.conf: No such file or directory
+ sed -i '/tracker_server =/d' ./client.conf
sed: can't read ./client.conf: No such file or directory
+ sed -i '21atracker_server =localhost' ./client.conf
sed: can't read ./client.conf: No such file or directory
+ sed -i '/base_path/s/\/home\/yuqing\/fastdfs/\/tmp\/guochenyang\/2/g' ./tracker.conf
sed: can't read ./tracker.conf: No such file or directory
+ sed -i /thread_stack_size/s/256KB/1024KB/g ./tracker.conf
sed: can't read ./tracker.conf: No such file or directory
+ sed -i '/base_path/s/\/home\/yuqing\/fastdfs/\/tmp\/guochenyang\/3/g' ./storage.conf
sed: can't read ./storage.conf: No such file or directory
+ sed -i '/store_path0/s/\/home\/yuqing\/fastdfs/\/tmp\/guochenyang\/3/g' ./storage.conf
sed: can't read ./storage.conf: No such file or directory
+ sed -i '/tracker_server =/d' ./storage.conf
sed: can't read ./storage.conf: No such file or directory
+ sed -i '144atracker_server =localhost' ./storage.conf
sed: can't read ./storage.conf: No such file or directory
+ echo hello
+ echo world
+ storage_path=/root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Wed Apr  5 22:07:30 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Apr  5 22:07:31 2023 - INFO  - Start to run test.
+ fdfs_trackerd ./tracker.conf start
[2023-04-05 22:07:31] ERROR - file: shared_func.c, line: 1301, file /root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/./tracker.conf not exist
[2023-04-05 22:07:31] ERROR - file: process_ctrl.c, line: 291, load conf file "./tracker.conf" fail, ret code: 2
[2023-04-05 22:07:31] ERROR - file: shared_func.c, line: 1301, file /root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/./tracker.conf not exist
[2023-04-05 22:07:31] ERROR - file: tracker_func.c, line: 155, load conf file "./tracker.conf" fail, ret code: 2
[2023-04-05 22:07:31] CRIT - exit abnormally!

+ CHECK_RESULT 2 0 0 'Check fdfs_trackerd start failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_trackerd start failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check fdfs_trackerd start failed.'
+ LOG_ERROR 'Check fdfs_trackerd start failed.'
+ message='Check fdfs_trackerd start failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fdfs_trackerd start failed.'
Wed Apr  5 22:07:32 2023 - ERROR - Check fdfs_trackerd start failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fastdfs_02.sh line 29'
+ message='oe_test_fastdfs_02.sh line 29'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fastdfs_02.sh line 29'
Wed Apr  5 22:07:33 2023 - ERROR - oe_test_fastdfs_02.sh line 29
+ '[' 0 -eq 1 ']'
+ return 0
+ netstat -unltp
+ grep fdfs_trackerd
+ CHECK_RESULT 1 0 0 'Check fdfs_trackerd start error failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_trackerd start error failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fdfs_trackerd start error failed.'
+ LOG_ERROR 'Check fdfs_trackerd start error failed.'
+ message='Check fdfs_trackerd start error failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fdfs_trackerd start error failed.'
Wed Apr  5 22:07:34 2023 - ERROR - Check fdfs_trackerd start error failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fastdfs_02.sh line 31'
+ message='oe_test_fastdfs_02.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fastdfs_02.sh line 31'
Wed Apr  5 22:07:35 2023 - ERROR - oe_test_fastdfs_02.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ fdfs_storaged /root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/storage.conf start
[2023-04-05 22:07:35] ERROR - file: shared_func.c, line: 1301, file /root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/storage.conf not exist
[2023-04-05 22:07:35] ERROR - file: process_ctrl.c, line: 291, load conf file "/root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/storage.conf" fail, ret code: 2
+ CHECK_RESULT 0 0 0 'Check fdfs_storaged start failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_storaged start failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
[2023-04-05 22:07:35] ERROR - file: shared_func.c, line: 1301, file /root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/storage.conf not exist
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
[2023-04-05 22:07:35] ERROR - file: storage_func.c, line: 1425, load conf file "/root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/storage.conf" fail, ret code: 2
[2023-04-05 22:07:35] CRIT - exit abnormally!

+ netstat -unltp
+ grep storaged
+ CHECK_RESULT 1 0 0 'Check fdfs_storaged start error failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_storaged start error failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fdfs_storaged start error failed.'
+ LOG_ERROR 'Check fdfs_storaged start error failed.'
+ message='Check fdfs_storaged start error failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fdfs_storaged start error failed.'
Wed Apr  5 22:07:42 2023 - ERROR - Check fdfs_storaged start error failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fastdfs_02.sh line 36'
+ message='oe_test_fastdfs_02.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fastdfs_02.sh line 36'
Wed Apr  5 22:07:43 2023 - ERROR - oe_test_fastdfs_02.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ fdfs_crc32 client.conf
file: fdfs_crc32.c, line: 43, open file client.conf fail, errno: 2, error info: No such file or directory
+ CHECK_RESULT 2 0 0 'Check fdfs_crc32 failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_crc32 failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check fdfs_crc32 failed.'
+ LOG_ERROR 'Check fdfs_crc32 failed.'
+ message='Check fdfs_crc32 failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fdfs_crc32 failed.'
Wed Apr  5 22:07:44 2023 - ERROR - Check fdfs_crc32 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fastdfs_02.sh line 38'
+ message='oe_test_fastdfs_02.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fastdfs_02.sh line 38'
Wed Apr  5 22:07:45 2023 - ERROR - oe_test_fastdfs_02.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ fdfs_download_file --help
+ grep Usage: ./usage.txt
Usage: fdfs_download_file <config_file> <file_id> [local_filename] [<download_offset> <download_bytes>]
+ CHECK_RESULT 0 0 0 'Check fdfs_download_file --help failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_download_file --help failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ fdfs_upload_appender client.conf test1.txt
[2023-04-05 22:07:45] ERROR - file: shared_func.c, line: 1301, file /root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/client.conf not exist
[2023-04-05 22:07:45] ERROR - file: ../client/client_func.c, line: 429, load conf file "client.conf" fail, ret code: 2
+ appender_file=
+ fdfs_download_file client.conf
Usage: fdfs_download_file <config_file> <file_id> [local_filename] [<download_offset> <download_bytes>]
+ CHECK_RESULT 1 0 0 'Check fdfs_download_file failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_download_file failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fdfs_download_file failed.'
+ LOG_ERROR 'Check fdfs_download_file failed.'
+ message='Check fdfs_download_file failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fdfs_download_file failed.'
Wed Apr  5 22:07:46 2023 - ERROR - Check fdfs_download_file failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fastdfs_02.sh line 44'
+ message='oe_test_fastdfs_02.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fastdfs_02.sh line 44'
Wed Apr  5 22:07:47 2023 - ERROR - oe_test_fastdfs_02.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ fdfs_file_info --help
+ grep Usage: ./usage1.txt
Usage: fdfs_file_info <config_file> <file_id>
+ CHECK_RESULT 0 0 0 'Check fdfs_file_info --help failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_file_info --help failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fdfs_file_info client.conf
+ grep 'file type: appender'
+ CHECK_RESULT 1 0 0 'Check fdfs_file_info failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_file_info failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fdfs_file_info failed.'
+ LOG_ERROR 'Check fdfs_file_info failed.'
+ message='Check fdfs_file_info failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fdfs_file_info failed.'
Wed Apr  5 22:07:48 2023 - ERROR - Check fdfs_file_info failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fastdfs_02.sh line 49'
+ message='oe_test_fastdfs_02.sh line 49'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fastdfs_02.sh line 49'
Wed Apr  5 22:07:49 2023 - ERROR - oe_test_fastdfs_02.sh line 49
+ '[' 0 -eq 1 ']'
+ return 0
+ fdfs_delete_file --help
+ grep Usage: ./usage2.txt
Usage: fdfs_delete_file <config_file> <file_id>
+ CHECK_RESULT 0 0 0 'Check fdfs_delete_file --help failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_delete_file --help failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fdfs_delete_file client.conf
Usage: fdfs_delete_file <config_file> <file_id>
+ CHECK_RESULT 1 0 0 'Check fdfs_delete_file failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_delete_file failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fdfs_delete_file failed.'
+ LOG_ERROR 'Check fdfs_delete_file failed.'
+ message='Check fdfs_delete_file failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fdfs_delete_file failed.'
Wed Apr  5 22:07:50 2023 - ERROR - Check fdfs_delete_file failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fastdfs_02.sh line 54'
+ message='oe_test_fastdfs_02.sh line 54'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fastdfs_02.sh line 54'
Wed Apr  5 22:07:51 2023 - ERROR - oe_test_fastdfs_02.sh line 54
+ '[' 0 -eq 1 ']'
+ return 0
+ fdfs_trackerd ./tracker.conf stop
[2023-04-05 22:07:51] ERROR - file: shared_func.c, line: 1301, file /root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/./tracker.conf not exist
[2023-04-05 22:07:51] ERROR - file: process_ctrl.c, line: 291, load conf file "./tracker.conf" fail, ret code: 2
pid file: /tmp/data/fdfs_trackerd.pid not exist!
+ CHECK_RESULT 2 0 0 'Check fdfs_trackerd stop failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_trackerd stop failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check fdfs_trackerd stop failed.'
+ LOG_ERROR 'Check fdfs_trackerd stop failed.'
+ message='Check fdfs_trackerd stop failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fdfs_trackerd stop failed.'
Wed Apr  5 22:07:52 2023 - ERROR - Check fdfs_trackerd stop failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fastdfs_02.sh line 56'
+ message='oe_test_fastdfs_02.sh line 56'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fastdfs_02.sh line 56'
Wed Apr  5 22:07:53 2023 - ERROR - oe_test_fastdfs_02.sh line 56
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5 'fdfs_storaged /root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/storage.conf stop' 2
+ wait_time=5
+ cmd='fdfs_storaged /root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/storage.conf stop'
+ mode=2
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd 'fdfs_storaged /root/mugen/testcases/cli-test/fastdfs/oe_test_fastdfs_02/storage.conf stop' --mode 2
+ CHECK_RESULT 0 0 0 'Check fdfs_storaged stop failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fdfs_storaged stop failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed Apr  5 22:08:01 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Apr  5 22:08:02 2023 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Apr  5 22:08:03 2023 - INFO  - Start to restore the test environment.
+ rm -rf test1.txt test2.txt usage1.txt usage2.txt usage.txt
+ Post_Test
+ rm -rf ./client.conf ./storage.conf ./tracker.conf /tmp/guochenyang
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp34fz2_0g ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp34fz2_0g
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed Apr  5 22:08:34 2023 - INFO  - End to restore the test environment.
